# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [0.139741, -0.340811, -0.478618]
rotation: [0.00592865, -0.0265964, 0.10933, 0.993632]
frame_id: camera_1_link
child_frame_id: setup1/panda_link0
